# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_table_order_orderitem_cart_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
