# Generated by Django 5.2.7 on 2025-11-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_alter_product_category_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Ayurvedic Treatment', 'Ayurvedic Treatment'), ('Ayurvedic Tips', 'Ayurvedic Tips'), ('Remedies', 'Remedies to Manage Hypertension'), ('Natural Remedies', 'Natural Ayurvedic Remedies for Throat Infection Relief'), ('Women’s Wellness', 'Women’s Wellness'), ('Skin Wellness', 'Skin Wellness'), ('Pain Reliever', 'Pain Reliever'), ('Immunity Wellness', 'Immunity Wellness'), ('Diabetic Wellness', 'Diabetic Wellness'), ('Blood Purifier', 'Blood Purifier')], default='Ayurvedic Tips', max_length=50),
        ),
    ]
